# Generated by Django 3.0.5 on 2020-04-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0003_auto_20200416_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server',
        ),
    ]
