# Generated by Django 3.0.5 on 2020-04-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0001_initial'),
        ('webpanel', '0004_delete_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('player_count', models.IntegerField()),
                ('max_player', models.IntegerField()),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Server')),
            ],
        ),
    ]
